apiVersion: v1

kind: PersistentVolume

metadata:

  name: wp-pv

spec:

  storageClassName: standard

  capacity:

    storage: 1Gi

  accessModes:

    - ReadWriteMany

  hostPath:

    path: /mnt/data
